openapi: 3.0.0
info:
  title: Ecommerce Store API
  description: Learning to create secure API for store
  version: 1.1.0
  # contact:
  #   email: rsinha488@gmail.com
#servers:
#  - url: http://localhost:4000/api/v1
#    description: for local host - secure  
#  - url: http://localhost:4000/api/v1
#    description: for localhost regular
servers:
 - url: "{protocol}://localhost:4000/api/{version}"
   description: for local host 
   variables:
    version:
      enum:
        - v1
        - v2
      default: v1
    protocol:
      enum:
        - http
        - https
      default: http
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
        in: cookie
        name: token
      BearerAuth:
        type: http
        scheme: bearer
paths:
  /dummy:
    get:
      tags:
        - Home
      summary: returns a greet message.
      responses:
        '200':    # status code
          description: All good success 
          content:
            application/json:
              schema: 
                type: string
                example: "myString"
        '400':
          description: Bad request
        '500':    
          description: internal server error 
